//SpacesUtils.canisterRegistry("asot_canister","Asot Canister","canister_partial_ln2",BlockID.spacescraft_helium_still)
SpacesUtils.canisterRegistry("h2o_canister","h2o Canister","cerosin_canister_partial",VanillaBlockID.water)
SpacesUtils.canisterRegistry("cerosin_canister","Kerosene Canister","cerosin_canister_partial",BlockID.spacescraft_cerosin_still)
SpacesUtils.canisterRegistry("fuel_canister","Clean Fuel Canister","Fuel_Canister_Partial",BlockID.spacescraft_bad_fuel_still)
//SpacesUtils.canisterRegistry("masut_canister","Masut Canister","masut_canister_partial",BlockID)
SpacesUtils.canisterRegistry("methane_canister","Methane Canister","methane_canister_partial",BlockID.spacescraft_methane_still)
SpacesUtils.canisterRegistry("oil_canister","Oil Canister","Oil_Canister_Partial",BlockID.spacescraft_oil_still)
SpacesUtils.canisterRegistry("rubber_canister","Rubber Canister","rubber_canister_partial",BlockID.spacescraft_rubber_still)